import { useEffect } from "react";

function App() {
  useEffect(() => {
    const base = import.meta.env.BASE_URL;
    const path = window.location.pathname;
    const basePath = base.replace(/\/$/, "");
    const relativePath = path.replace(basePath, "") || "/";

    if (relativePath.endsWith(".html")) return;

    // Redirect /home → /
    if (relativePath === "/home" || relativePath === "/home/") {
      window.location.replace(basePath + "/");
      return;
    }

    const pageMap: Record<string, string> = {
      "": "index.html",
      "/": "index.html",
      "/pricing": "pricing.html",
      "/pricing/": "pricing.html",
      "/about-us": "about-us.html",
      "/about-us/": "about-us.html",
      "/faq": "faq.html",
      "/faq/": "faq.html",
      "/contact": "contact.html",
      "/contact/": "contact.html",
      "/legal/terms-and-conditions": "terms-and-conditions.html",
      "/legal/terms-and-conditions/": "terms-and-conditions.html",
      "/legal/privacy-policy": "privacy-policy.html",
      "/legal/privacy-policy/": "privacy-policy.html",
      "/service-areas": "service-areas.html",
      "/service-areas/": "service-areas.html",
      "/washington-county": "washington-county.html",
      "/washington-county/": "washington-county.html",
      "/ozaukee-county": "ozaukee-county.html",
      "/ozaukee-county/": "ozaukee-county.html",
      "/fond-du-lac-county": "fond-du-lac-county.html",
      "/fond-du-lac-county/": "fond-du-lac-county.html",
      "/sheboygan-county": "sheboygan-county.html",
      "/sheboygan-county/": "sheboygan-county.html",
      "/waukesha-county": "waukesha-county.html",
      "/waukesha-county/": "waukesha-county.html",
      "/west-bend": "west-bend.html",
      "/west-bend/": "west-bend.html",
      "/germantown": "germantown.html",
      "/germantown/": "germantown.html",
      "/hartford": "hartford.html",
      "/hartford/": "hartford.html",
      "/slinger": "slinger.html",
      "/slinger/": "slinger.html",
      "/jackson": "jackson.html",
      "/jackson/": "jackson.html",
      "/kewaskum": "kewaskum.html",
      "/kewaskum/": "kewaskum.html",
      "/richfield": "richfield.html",
      "/richfield/": "richfield.html",
      "/barton": "barton.html",
      "/barton/": "barton.html",
      "/newburg": "newburg.html",
      "/newburg/": "newburg.html",
      "/allenton": "allenton.html",
      "/allenton/": "allenton.html",
      "/erin": "erin.html",
      "/erin/": "erin.html",
      "/addison": "addison.html",
      "/addison/": "addison.html",
      "/cedarburg": "cedarburg.html",
      "/cedarburg/": "cedarburg.html",
      "/port-washington": "port-washington.html",
      "/port-washington/": "port-washington.html",
      "/grafton": "grafton.html",
      "/grafton/": "grafton.html",
      "/mequon": "mequon.html",
      "/mequon/": "mequon.html",
      "/thiensville": "thiensville.html",
      "/thiensville/": "thiensville.html",
      "/saukville": "saukville.html",
      "/saukville/": "saukville.html",
      "/fredonia": "fredonia.html",
      "/fredonia/": "fredonia.html",
      "/belgium": "belgium.html",
      "/belgium/": "belgium.html",
      "/river-hills": "river-hills.html",
      "/river-hills/": "river-hills.html",
      "/fond-du-lac": "fond-du-lac.html",
      "/fond-du-lac/": "fond-du-lac.html",
      "/ripon": "ripon.html",
      "/ripon/": "ripon.html",
      "/waupun": "waupun.html",
      "/waupun/": "waupun.html",
      "/mayville": "mayville.html",
      "/mayville/": "mayville.html",
      "/campbellsport": "campbellsport.html",
      "/campbellsport/": "campbellsport.html",
      "/north-fond-du-lac": "north-fond-du-lac.html",
      "/north-fond-du-lac/": "north-fond-du-lac.html",
      "/lomira": "lomira.html",
      "/lomira/": "lomira.html",
      "/oakfield": "oakfield.html",
      "/oakfield/": "oakfield.html",
      "/rosendale": "rosendale.html",
      "/rosendale/": "rosendale.html",
      "/brandon": "brandon.html",
      "/brandon/": "brandon.html",
      "/eden": "eden.html",
      "/eden/": "eden.html",
      "/brownsville": "brownsville.html",
      "/brownsville/": "brownsville.html",
      "/sheboygan": "sheboygan.html",
      "/sheboygan/": "sheboygan.html",
      "/sheboygan-falls": "sheboygan-falls.html",
      "/sheboygan-falls/": "sheboygan-falls.html",
      "/plymouth": "plymouth.html",
      "/plymouth/": "plymouth.html",
      "/kohler": "kohler.html",
      "/kohler/": "kohler.html",
      "/elkhart-lake": "elkhart-lake.html",
      "/elkhart-lake/": "elkhart-lake.html",
      "/oostburg": "oostburg.html",
      "/oostburg/": "oostburg.html",
      "/random-lake": "random-lake.html",
      "/random-lake/": "random-lake.html",
      "/cedar-grove": "cedar-grove.html",
      "/cedar-grove/": "cedar-grove.html",
      "/kiel": "kiel.html",
      "/kiel/": "kiel.html",
      "/howards-grove": "howards-grove.html",
      "/howards-grove/": "howards-grove.html",
      "/waldo": "waldo.html",
      "/waldo/": "waldo.html",
      "/cascade": "cascade.html",
      "/cascade/": "cascade.html",
      "/waukesha": "waukesha.html",
      "/waukesha/": "waukesha.html",
      "/brookfield": "brookfield.html",
      "/brookfield/": "brookfield.html",
      "/pewaukee": "pewaukee.html",
      "/pewaukee/": "pewaukee.html",
      "/oconomowoc": "oconomowoc.html",
      "/oconomowoc/": "oconomowoc.html",
      "/menomonee-falls": "menomonee-falls.html",
      "/menomonee-falls/": "menomonee-falls.html",
      "/new-berlin": "new-berlin.html",
      "/new-berlin/": "new-berlin.html",
      "/muskego": "muskego.html",
      "/muskego/": "muskego.html",
      "/mukwonago": "mukwonago.html",
      "/mukwonago/": "mukwonago.html",
      "/sussex": "sussex.html",
      "/sussex/": "sussex.html",
      "/delafield": "delafield.html",
      "/delafield/": "delafield.html",
      "/wales": "wales.html",
      "/wales/": "wales.html",
      "/hartland": "hartland.html",
      "/hartland/": "hartland.html",
      "/elm-grove": "elm-grove.html",
      "/elm-grove/": "elm-grove.html",
      "/dousman": "dousman.html",
      "/dousman/": "dousman.html",
      "/demolition-debris-removal": "demolition-debris-removal.html",
      "/demolition-debris-removal/": "demolition-debris-removal.html",
      "/small-structure-teardowns": "small-structure-teardowns.html",
      "/small-structure-teardowns/": "small-structure-teardowns.html",
      "/estate-cleanouts": "estate-cleanouts.html",
      "/estate-cleanouts/": "estate-cleanouts.html",
      "/hoarder-cleanouts": "hoarder-cleanouts.html",
      "/hoarder-cleanouts/": "hoarder-cleanouts.html",
      "/house-cleanouts": "house-cleanouts.html",
      "/house-cleanouts/": "house-cleanouts.html",
      "/garage-cleanouts": "garage-cleanouts.html",
      "/garage-cleanouts/": "garage-cleanouts.html",
      "/basement-cleanouts": "basement-cleanouts.html",
      "/basement-cleanouts/": "basement-cleanouts.html",
      "/rental-property-cleanouts": "rental-property-cleanouts.html",
      "/rental-property-cleanouts/": "rental-property-cleanouts.html",
      "/commercial-junk-removal": "commercial-junk-removal.html",
      "/commercial-junk-removal/": "commercial-junk-removal.html",
      "/furniture-removal": "furniture-removal.html",
      "/furniture-removal/": "furniture-removal.html",
      "/appliance-removal": "appliance-removal.html",
      "/appliance-removal/": "appliance-removal.html",
      "/mattress-removal": "mattress-removal.html",
      "/mattress-removal/": "mattress-removal.html",
      "/yard-debris-removal": "yard-debris-removal.html",
      "/yard-debris-removal/": "yard-debris-removal.html",
      "/construction-debris-removal": "construction-debris-removal.html",
      "/construction-debris-removal/": "construction-debris-removal.html",
      "/demolition": "demolition.html",
      "/demolition/": "demolition.html",
      "/shed-removal": "shed-removal.html",
      "/shed-removal/": "shed-removal.html",
      "/hot-tub-removal": "hot-tub-removal.html",
      "/hot-tub-removal/": "hot-tub-removal.html",
      "/deck-removal": "deck-removal.html",
      "/deck-removal/": "deck-removal.html",
      "/fence-removal": "fence-removal.html",
      "/fence-removal/": "fence-removal.html",
      "/playset-removal": "playset-removal.html",
      "/playset-removal/": "playset-removal.html",
      "/cabinet-removal": "cabinet-removal.html",
      "/cabinet-removal/": "cabinet-removal.html",
      "/flooring-removal": "flooring-removal.html",
      "/flooring-removal/": "flooring-removal.html",
      "/interior-demolition": "interior-demolition.html",
      "/interior-demolition/": "interior-demolition.html",
      "/dodge-county": "dodge-county.html",
      "/dodge-county/": "dodge-county.html",
      "/watertown": "watertown.html",
      "/watertown/": "watertown.html",
      "/juneau": "juneau.html",
      "/juneau/": "juneau.html",
    };

    const target = pageMap[relativePath] ?? "index.html";
    window.location.replace(`${basePath}/${target}`);
  }, []);

  return (
    <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: "100vh" }}>
      <p>Loading…</p>
    </div>
  );
}

export default App;
